### ISSUE TITLE
[BUG] [UE] The connection to the server has been lost.

### ISSUE THREAD

**Issue by mehmetyagci** [scalehq/lhq#3]
### Unhandled Exception

`The connection to the server has been lost.`

**Occured at**

`2021-01-19T18:55:05.607Z` (UTC)

**Full Exception**

```
- Exception was handled
- type: Microsoft.VisualStudio.WinForms.RemoteClient.DesignToolsClientException
- message: The connection to the server has been lost.
- source: Microsoft.VisualStudio.WinForms.RemoteClient
- stack trace:    at Microsoft.VisualStudio.WinForms.RemoteClient.DesignToolsClient.<SendRequestAsync>d__49`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudio.WinForms.RemoteClient.DesignToolsClient.Microsoft.DotNet.DesignTools.Protocol.Endpoints.IRequestSender.SendRequest[TRequest,TResponse](String name, TRequest request)
   at Microsoft.VisualStudio.WinForms.Protocol.Endpoints.Components.GetFullComponentNameEndpoint.Sender.SendRequest(IComponent component)
   at Microsoft.VisualStudio.WinForms.Protocol.Endpoints.WinFormsEndpoints.ComponentsImpl.GetFullComponentName(IComponent component)
   at Microsoft.VisualStudio.WinForms.RemoteClient.Proxies.ComponentProxy.GetFullComponentName()
   at Microsoft.VisualStudio.WinForms.RemoteClient.Proxies.ObjectProxyTypeDescriptor.GetComponentName()
   at System.ComponentModel.TypeDescriptionProvider.GetFullComponentName(Object component)
   at System.ComponentModel.TypeDescriptor.TypeDescriptionNode.GetFullComponentName(Object component)
   at System.ComponentModel.TypeDescriptor.GetFullComponentName(Object component)
   at Microsoft.VisualStudio.PropertyBrowser.CBEntry.get_Name()
   at Microsoft.VisualStudio.PropertyBrowser.CBEntry.ToString()
   at System.Convert.ToString(Object value, IFormatProvider provider)
   at System.Windows.Forms.ListControl.GetItemText(Object item)
   at System.Windows.Forms.ComboBox.NativeAdd(Object item)
   at System.Windows.Forms.ComboBox.OnHandleCreated(EventArgs e)
   at Microsoft.VisualStudio.PropertyBrowser.PBComboBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at Microsoft.VisualStudio.PropertyBrowser.MSOComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
- has inner exception: no
```

**Environment**

**OS**

Microsoft Windows NT 10.0.18363.0

**Visual Studio Version**

2019

**Visual Studio Edition**

Community

**Extension Version**

`1.2.0.0`

**Comment by psulek** [comment]
Can you specify more details, like where exactly did you get this error. In editor? when saving ? after add new resouces? on generation of C# classes?

**Comment by psulek** [comment]
Inactive, cant reproduce - closing.
